//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfyaPro_ServerAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AfyaPro_ServerAdmin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Table structure for table afya_dhis_period */
        ///
        ///CREATE TABLE afya_dhis_period (
        ///  periodid int(11) NOT NULL auto_increment,
        ///  periodtypeid int(11) default NULL,
        ///  startdate date NOT NULL,
        ///  enddate date NOT NULL,
        ///  PRIMARY KEY  (periodid),
        ///  UNIQUE KEY periodtypeid (periodtypeid,startdate,enddate)
        ///) ENGINE=InnoDB DEFAULT CHARSET=latin1;
        ///
        ////*Table structure for table billaccountfromtowhom */
        ///
        ///CREATE TABLE billaccountfromtowhom (
        ///  autocode int(11) NOT NULL auto_increment,
        ///  description varchar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newdb_mssqlserver {
            get {
                return ResourceManager.GetString("newdb_mssqlserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Table structure for table afya_dhis_period */
        ///
        ///CREATE TABLE afya_dhis_period (
        ///  periodid int(11) NOT NULL auto_increment,
        ///  periodtypeid int(11) default NULL,
        ///  startdate date NOT NULL,
        ///  enddate date NOT NULL,
        ///  PRIMARY KEY  (periodid),
        ///  UNIQUE KEY periodtypeid (periodtypeid,startdate,enddate)
        ///) ENGINE=InnoDB DEFAULT CHARSET=latin1;
        ///
        ////*Table structure for table billaccountfromtowhom */
        ///
        ///CREATE TABLE billaccountfromtowhom (
        ///  autocode int(11) NOT NULL auto_increment,
        ///  description varchar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newdb_mysql {
            get {
                return ResourceManager.GetString("newdb_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///SQLyog Enterprise - MySQL GUI v8.05 
        ///MySQL - 5.0.21-community-nt : Database - hmis
        ///*********************************************************************
        ///*/
        ///
        ///
        ////*!40101 SET NAMES utf8 */;
        ///
        ////*!40101 SET SQL_MODE=&apos;&apos;*/;
        ///
        ////*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=&apos;NO_AUTO_VALUE_ON_ZERO&apos; */;
        ///
        ////*Table structure for table `afya_dhis_period` */
        ///
        ///DROP TABLE IF EXISTS `afya_dhis_period`;
        ///
        ///CREATE TABLE `afya_dhis_period` (
        ///  `periodid` int(11) NOT NULL auto_increment,
        ///  `periodtypeid` int(11)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string settings_mysql {
            get {
                return ResourceManager.GetString("settings_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*View view_billinvoicedoc*/ 
        ///CREATE
        ///    VIEW view_billinvoicedoc 
        ///    AS       
        ///SELECT
        ///    bi.transdate
        ///    , bi.invoiceno
        ///    , bi.patientcode
        ///    , bi.patientsurname
        ///    , bi.patientfirstname
        ///    , bi.patientothernames
        ///    , bi.patientfirstname + &apos; &apos; + bi.patientothernames + &apos; &apos; + bi.patientsurname patientfullname
        ///    , bi.patientgender
        ///    , bi.patientbirthdate
        ///    , CONVERT(INT,Datediff(day, bi.patientbirthdate, bi.transdate)/365.25) patientage
        ///    , bi.patientstreet
        ///    , bi.currencyco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string views_mssqlserver {
            get {
                return ResourceManager.GetString("views_mssqlserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*View view_billinvoicedoc*/ 
        ///DROP VIEW IF EXISTS view_billinvoicedoc;
        ///CREATE
        ///    VIEW view_billinvoicedoc 
        ///    AS       
        ///SELECT
        ///    fo.facilitycode
        ///    , fo.facilitydescription
        ///    , fo.box
        ///    , fo.street
        ///    , fo.teleno
        ///    , fo.headname
        ///    , fo.headdesignation
        ///    , fo.countrycode
        ///    , fo.countrydescription
        ///    , fo.regioncode
        ///    , fo.regiondescription
        ///    , fo.districtcode
        ///    , fo.districtdescription 
        ///    , bi.transdate
        ///    , bi.voidtransdate
        ///    , bi.invoiceno
        ///    , bi.voidno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string views_mysql {
            get {
                return ResourceManager.GetString("views_mysql", resourceCulture);
            }
        }
    }
}
